{% set name = "kwindowsystem" %}
{% set version = "5.74.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kwindowsystem-{{ version }}.tar.xz
  sha256: 33da54b0f76a661919445c9352c04cc23f9b6a0f4c842a76aa810091ca09b12f

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kwindowsystem', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - xorg-libx11
    - qt
    - libxcb
    - xcb-util
    - xcb-util-wm
    - xcb-util-keysyms
    - xorg-libxrender
  run:
    - xorg-libxfixes
    - xorg-libx11
    - libxcb

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5WindowSystem.so

about:
  home: https://api.kde.org/frameworks/kwindowsystem/html/index.html
  license: LGPL-v2.1-or-later
  license_family: GPL
  license_file: COPYING.LIB
  summary: Access to the windowing system
  description: |
    Convenience access to certain properties and features of the windowing system.
  dev_url: https://cgit.kde.org/kwindowsystem.git/tree

extra:
  recipe-maintainers:
    - scopatz
