{% set name = "kwindowsystem" %}
{% set version = "5.112.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/kwindowsystem-{{ version }}.tar.xz
  sha256: 418e13e52f66a4030757d8479c787adab1112f40f694c0cc26309d84bf793022

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('kwindowsystem', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - extra-cmake-modules >={{ version }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
  host:
    - xorg-libxfixes  # [linux]
    - xorg-libxext
    - xorg-libx11
    - qt
    - libxcb
    - xcb-util
    - xcb-util-wm
    - xcb-util-keysyms
    - xorg-libxrender
  run:
    - xorg-libxfixes
    - xorg-libx11
    - libxcb

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5WindowSystem.so

about:
  home: https://api.kde.org/frameworks/kwindowsystem/html/index.html
  license: LGPL-2.1-only AND LGPL-2.1-or-later AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-LGPL AND MIT
  license_file:
    - LICENSES/LGPL-2.1-only.txt
    - LICENSES/LGPL-2.1-or-later.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
    - LICENSES/MIT.txt
  summary: Access to the windowing system
  description: |
    Convenience access to certain properties and features of the windowing system.
  dev_url: https://cgit.kde.org/kwindowsystem.git/tree

extra:
  recipe-maintainers:
    - scopatz
