travis:
  secure:
    BINSTAR_TOKEN: MkQn39cLtnUGyRsZcSdmBWedU6kPOpkQJiQGhaVD/1tsz/oyy4rbPuxJXT9BRhsJPRTR0FN8elGAy8prKrrJY3ZYpwlNyjYoE4B+7IpVtijJyJzD7oDrJRTx55jMQtGDTBGPtPfHGSQdSfIwJqi/jsFfGcoL+m933pSowvcirwx6G4vIPmckF6Dc4iJk2LQs+67JvmeNd6FMM9q+ovY16XLSEQKv2WcdyZnUGiNY5DAEsUk1HBBfh8u3jl48xwatoA2R/iemEkhwBHRbkFgv2u/ez7dCJXMQqRrq8I+OUvOnpRJ6E/e5uMeAS+dADyznv2VaJbmcX5l4cG6J+xe3drv6kR06Gvy4F88e0S2S14vdpRQaQkyvSZiJRV8LOpqfqHJNLvNZqewxMutS9D/0zeZ78fszNg4/aw7ueQgIESW89eO4JSpldNohCtxE7H4DdgvsrKXLhp3h/k5mss3nAEBwZxCMHaYnHUU2G09gCWwtU3izafpwvtHi6OWByg2WyPH7JnJwU8YSpb63mFGoPbbwcVNUo71pReTo24JbAjJOyKH00PumAbayvag1XMxe+dSMbhhvfinfPAZSnq4kpPrIVrwaIwI+F/zVu6v5ys3yyW7b6uwIXZqhdNrXKfpee6T+0oZn7A2DCy35G0Bi6cO2G+NoHvO81PuU7IGmNRY=
conda_forge_output_validation: true
bot:
  check_solvable: True
